// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: pmm — *2222  (reference: pmm_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [10, 0], [10, 15], [0, 15]]);
}

module FundamentalCut()
{
    polygon(points = [
            [2.93606, 15],
            [4.07387, 14.94259],
            [5.11185, 14.73045],
            [6.04997, 14.36358],
            [6.88825, 13.84199],
            [7.62668, 13.16567],
            [8.26526, 12.33462],
            [8.804, 11.34884],
            [9.2429, 10.20833],
            [9.58194, 8.9131],
            [9.82114, 7.46314],
            [9.96049, 5.85845],
            [10, 4.09904],
            [10, 15]
    ]);
    polygon(points = [
            [8.58269, 4.09904],
            [8.38879, 5.4942],
            [8.14459, 6.78498],
            [7.85009, 7.97136],
            [7.50529, 9.05337],
            [7.11019, 10.03098],
            [6.66478, 10.90421],
            [6.16908, 11.67305],
            [5.62308, 12.3375],
            [5.02677, 12.89757],
            [4.38017, 13.35325],
            [3.68326, 13.70454],
            [2.93606, 13.95144],
            [2.91605, 13.74916],
            [2.86899, 13.57067],
            [2.79489, 13.41599],
            [2.69375, 13.2851],
            [2.56556, 13.17801],
            [2.41034, 13.09471],
            [2.22806, 13.03522],
            [2.01875, 12.99952],
            [1.78239, 12.98762],
            [1.51899, 12.99952],
            [1.22855, 13.03522],
            [0.91106, 13.09471],
            [1.28074, 12.78939],
            [1.59796, 12.48353],
            [1.86271, 12.17713],
            [2.075, 11.87019],
            [2.23483, 11.56271],
            [2.34219, 11.25469],
            [2.39709, 10.94612],
            [2.39952, 10.63702],
            [2.34949, 10.32737],
            [2.247, 10.01719],
            [2.09204, 9.70646],
            [1.88462, 9.39519],
            [2.52257, 9.54014],
            [3.13834, 9.54663],
            [3.73194, 9.41466],
            [4.30337, 9.14423],
            [4.85261, 8.73534],
            [5.37969, 8.18798],
            [5.88459, 7.50216],
            [6.36731, 6.67788],
            [6.82785, 5.71514],
            [7.26623, 4.61394],
            [7.68242, 3.37428],
            [8.07644, 1.99615]
    ]);
    translate([0, 0]) circle(r = 7.22524, $fn = 64);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() mirror([1, 0, 0]) FundamentalRemains();
        weld() mirror([0, 1, 0]) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*20 + j*0, i*0 + j*30, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(1.5) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
