// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p4 — 442  (reference: p4_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [0, 0.5], [0.5, 0.5], [0.5, 0]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0.0488, 0.44947],
            [0.44861, 0.05226],
            [0.43532, 0.07769],
            [0.42445, 0.10076],
            [0.41599, 0.12146],
            [0.40995, 0.13981],
            [0.40633, 0.15579],
            [0.40512, 0.16941],
            [0.40633, 0.18067],
            [0.40995, 0.18957],
            [0.41599, 0.1961],
            [0.42445, 0.20028],
            [0.43532, 0.20209],
            [0.44861, 0.20154],
            [0.44702, 0.25064],
            [0.44269, 0.29237],
            [0.43562, 0.32672],
            [0.42582, 0.3537],
            [0.41327, 0.37331],
            [0.39798, 0.38554],
            [0.37995, 0.3904],
            [0.35918, 0.38788],
            [0.33567, 0.378],
            [0.30942, 0.36073],
            [0.28043, 0.3361],
            [0.2487, 0.30409],
            [0.09942, 0.44947]
    ]);
    polygon(points = [
            [0.07346, 0.30409],
            [0.10185, 0.30273],
            [0.12773, 0.29781],
            [0.1511, 0.28932],
            [0.17197, 0.27726],
            [0.19033, 0.26163],
            [0.20619, 0.24243],
            [0.21954, 0.21966],
            [0.23038, 0.19332],
            [0.23872, 0.16341],
            [0.24456, 0.12993],
            [0.24788, 0.09288],
            [0.2487, 0.05226],
            [0.15264, 0],
            [0, 0],
            [0.0312, 0.01663],
            [0.05746, 0.03223],
            [0.07879, 0.0468],
            [0.09519, 0.06033],
            [0.10665, 0.07283],
            [0.11319, 0.0843],
            [0.11479, 0.09474],
            [0.11145, 0.10415],
            [0.10319, 0.11252],
            [0.08999, 0.11986],
            [0.07186, 0.12617],
            [0.0488, 0.13144],
            [0.0488, 0.25216]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() rotate(90) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
        weld() rotate(270) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
