

// ----------------------------------------------------------------------
// Weld amount. Each assembly step grows the 2D shape by EPS, unions, then
// shrinks back by EPS — fusing the hairline seams between assembled pieces
// without changing the outer silhouette.
//
//   Increase EPS if seams still show.
//   Decrease EPS if thin features of your cut shapes start to fill in
//     (closing fills any gap/notch narrower than ~2*EPS).
// ----------------------------------------------------------------------
EPS = 0.002;
module weld(eps = EPS) {
    offset(delta = -eps) offset(delta = eps) children();
}
module rotate_about(a, p) {
    translate(p) rotate(a) translate([-p[0], -p[1]]) children();
}
module reflect_line(theta, p) {
    translate(p) rotate(theta) mirror([0,1,0]) rotate(-theta) translate([-p[0], -p[1]]) children();
}
module shapesToCut()
{
// Generated by OpenSCAD Fundamental Domain Editor
// Drawn inside the fundamental domain triangle:
//   [[-.25, sqrt(3)/4], [.75, sqrt(3)/4], [.25, sqrt(3)/12]]
// Each closed loop is emitted as its own polygon() below.
// Polygon 1, closed (5 points)
polygon(points = [
        [0.08121, 0.24179],
        [0.24538, 0.19868],
        [0.40967, 0.23652],
        [0.40967, 0.23652],
        [0.25, 0.14434]
]);
// Polygon 2, closed (4 points)
polygon(points = [
        [0.41385, 0.43301],
        [0.09077, 0.43301],
        [0.17385, 0.31406],
        [0.33769, 0.31175]
]);
}
module fundamentalDomain()
{
    polygon(points = [[.25,sqrt(3)/12], [-.25, sqrt(3)/4], [.75, sqrt(3)/4]]);
}
module cutFundamental()
{
    difference()
    {
        fundamentalDomain();
        shapesToCut();
    }
}
module equilateralTriangle()
{
    weld() {
        for (i = [0:1:2])
        {
            rotate_about(120*i, [.25,sqrt(3)/12]) cutFundamental();
        }
    }
}
// Step 3: the triangle plus its 180-degree copy -> parallelogram tile.
module parallelogram()
{
    weld() {
        equilateralTriangle();
        rotate(180) equilateralTriangle();
    }
}
gridStart= -5;
gridEnd = -gridStart;
module tileThePlane()
{
    weld()
    {
        for ( y = [gridStart:1:gridEnd])
        {
                    for ( x = [gridStart:1:gridEnd])
                    {translate([x, y*(sqrt(3)/2),0])parallelogram();
                    }
                }
            }
        }
tileThePlane();
        
color("green")cutFundamental();