// ----------------------------------------------------------------------
// Weld amount. Each assembly step grows the 2D shape by EPS, unions, then
// shrinks back by EPS — fusing the hairline seams between assembled pieces
// without changing the outer silhouette.
//
//   Increase EPS if seams still show.
//   Decrease EPS if thin features of your cut shapes start to fill in
//     (closing fills any gap/notch narrower than ~2*EPS).
// ----------------------------------------------------------------------
EPS = 0.002;

module weld(eps = EPS) {
    offset(delta = -eps) offset(delta = eps) children();
}

module rotate_about(a, p) {
    translate(p) rotate(a) translate([-p[0], -p[1]]) children();
}
module reflect_line(theta, p) {
    translate(p) rotate(theta) mirror([0,1,0]) rotate(-theta) translate([-p[0], -p[1]]) children();
}

module shapesToCut()
{
// Generated by OpenSCAD Fundamental Domain Drawer
// Drawn inside the fundamental domain triangle:
//   [[.25, sqrt(3)/12], [.25, sqrt(3)/4], [.75, sqrt(3)/4]]
// Each closed loop is emitted as its own polygon() below.

// Polygon 1, closed (3 points)
// Generated by OpenSCAD Fundamental Domain Drawer
// Drawn inside the fundamental domain triangle:
//   [[.25, sqrt(3)/12], [.25, sqrt(3)/4], [.75, sqrt(3)/4]]
// Each closed loop is emitted as its own polygon() below.

// Polygon 1, closed (25 points)
polygon(points = [
        [0.27385, 0.28221],
        [0.27072, 0.26082],
        [0.26929, 0.24261],
        [0.26955, 0.22758],
        [0.2715, 0.21573],
        [0.27515, 0.20706],
        [0.2805, 0.20156],
        [0.28754, 0.19925],
        [0.29627, 0.20011],
        [0.3067, 0.20416],
        [0.31882, 0.21138],
        [0.33264, 0.22179],
        [0.34815, 0.23537],
        [0.40903, 0.26589],
        [0.45771, 0.29157],
        [0.4942, 0.31241],
        [0.5185, 0.32841],
        [0.5306, 0.33958],
        [0.5305, 0.3459],
        [0.51821, 0.34739],
        [0.49373, 0.34403],
        [0.45705, 0.33584],
        [0.40818, 0.3228],
        [0.34711, 0.30493],
        [0.27385, 0.28221]
]);

// Polygon 2, closed (37 points)
polygon(points = [
        [0.60823, 0.41468],
        [0.63007, 0.41724],
        [0.64833, 0.41883],
        [0.66301, 0.41943],
        [0.67411, 0.41906],
        [0.68163, 0.4177],
        [0.68558, 0.41536],
        [0.68594, 0.41205],
        [0.68273, 0.40775],
        [0.67593, 0.40247],
        [0.66556, 0.39621],
        [0.65161, 0.38897],
        [0.63408, 0.38075],
        [0.62791, 0.38569],
        [0.62286, 0.38973],
        [0.61893, 0.39287],
        [0.61613, 0.39511],
        [0.61445, 0.39646],
        [0.61388, 0.39691],
        [0.61445, 0.39646],
        [0.61613, 0.39511],
        [0.61893, 0.39287],
        [0.62286, 0.38973],
        [0.62791, 0.38569],
        [0.63408, 0.38075],
        [0.57522, 0.38494],
        [0.52667, 0.38887],
        [0.48843, 0.39256],
        [0.4605, 0.39601],
        [0.44289, 0.39921],
        [0.43558, 0.40216],
        [0.43858, 0.40486],
        [0.45189, 0.40732],
        [0.47551, 0.40953],
        [0.50944, 0.41149],
        [0.55368, 0.41321],
        [0.60823, 0.41468]
]);
}

module fundamentalDomain()
{
    polygon(points = [[.25,sqrt(3)/12], [.25, sqrt(3)/4], [.75, sqrt(3)/4]]);
}

module cutFundamental()
{
    difference()
    {
        fundamentalDomain();
        shapesToCut();
    }
}

// Step 1: mirror the cut domain across the vertical edge -> isosceles half.
module isocelesTriangle()
{
    weld() {
        cutFundamental();
        reflect_line(90, [.25,sqrt(3)/12]) cutFundamental();
    }
}

// Step 2: three 120-degree copies about the apex -> equilateral triangle.
module equilateralTriangle()
{
    weld() {
        for (i = [0:1:2])
        {
            rotate_about(120*i, [.25,sqrt(3)/12]) isocelesTriangle();
        }
    }
}

// Step 3: the triangle plus its 180-degree copy -> parallelogram tile.
module parallelogram()
{
    weld() {
        equilateralTriangle();
        rotate(180) equilateralTriangle();
    }
}

gridStart= -5;
gridEnd = -gridStart;

module tileThePlane()
{
    weld()
    {
        for ( y = [gridStart:1:gridEnd])
        {
                    for ( x = [gridStart:1:gridEnd])
                    {translate([x, y*(sqrt(3)/2),0])parallelogram();
                    }
                }
            }
        }

tileThePlane();

        
color("green")cutFundamental();
