// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 2: 13 panels, stock 1200x600mm, 20mm edge padding, 3mm inter-panel gap

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_44_p4_FourDice.dxf");
translate([173.1544, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_45_pmg_PointAndPierce.dxf");
translate([251.3088, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_46_p6_LeafCorners.dxf");
translate([329.4632, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_47_p31m_IDontKnowMan.dxf");
translate([407.6175, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_48_p3_SixtySeven.dxf");
translate([485.7719, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_49_pmg_EmptyReverseWriting.dxf");
translate([563.9263, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_50_pgg_FingerSquares.dxf");
translate([642.0807, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_51_p4g_HollyStar.dxf");
translate([720.2351, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_52_p4m_InvisibleIntersection.dxf");
translate([798.3895, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_53_cmm_ParenthesisDiamond.dxf");
translate([876.5439, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_54_cm_ScaleShells.dxf");
translate([954.6983, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_55_p6m_SixFoldTriMesh.dxf");
translate([1032.8526, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_56_p3m1_TriDiamondMesh.dxf");
