// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 2: 1 panels, stock 1200x600mm, 20mm edge padding, 3mm inter-panel gap

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_56_p3m1_TriDiamondMesh.dxf");
