// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p6 — 632  (reference: p6_Template.scad)
//
// Fundamental domain has recursive circle-tree "bubble flowers" cut out of it.
// PatternArray() is a dense solid-tile-with-holes composite, so the golden
// triangle frame uses the nested difference() formula: the connective webbing
// stays as material and only the pattern's own cutouts become holes.

$fn = 32;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0.25, 0.14434], [-0.25, 0.43301], [0.75, 0.43301]]);
}

baseCase=.03;
module FundamentalCut()
{
    translate([.25,.43301,0])rotate(180)scale(.91)union()
    {
    DrawCircleL([0,0, 0], .1, [0,0,0], 0);
    DrawCircleR([0,0, 0], .1, [0,0,0], 0);
    DrawCircleU([0,0, 0], .1, [0,0,0], 0);
    translate([-.55,0,0])circle(r=.1);
    translate([.55,0,0])circle(r=.1);
    translate([-.25,0,0])circle(r=.05);
    translate([.25,0,0])circle(r=.05);

    }
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(120) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(240) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
        weld() rotate(180) translate([0.25, 0.14434]) rotate(120) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() rotate(180) translate([0.25, 0.14434]) rotate(240) translate([-0.25, -0.14434]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*0.86603, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 108, 0]) scale(38) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}


module DrawCircleR(center, size, previousCenter, previousSize)
{
    if (size >= baseCase)
    {
        difference()
        {
            translate(center) circle(r=size);
            translate(previousCenter) circle(r=previousSize*1.4);
        }
        DrawCircleR([center[0]+size*1.2, center[1] + size*1.2], size*.8, center, size);
    }
}

module DrawCircleL(center, size, previousCenter, previousSize)
{
    if (size >= baseCase)
    {
        difference()
        {
            translate(center) circle(r=size);
            translate(previousCenter) circle(r=previousSize*1.4);
        }
        DrawCircleL([center[0]-size*1.2, center[1] + size*1.2], size*.8, center, size);
    }
}

module DrawCircleU(center, size, previousCenter, previousSize)
{
    if (size >= baseCase)
    {
        difference()
        {
            translate(center) circle(r=size);
            translate(previousCenter) circle(r=previousSize*1.4);
        }
        DrawCircleU([center[0], center[1] + size*1.3], size*.8, center, size);
    }
}
