// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: pmm — *2222  (reference: pmm_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [10, 0], [10, 15], [0, 15]]);
}

module FundamentalCut()
{
    polygon(points = [
            [1, 14],
            [4, 4],
            [4, 12]
    ]);
    polygon(points = [
            [9, 14],
            [6, 4],
            [6, 12]
    ]);
    polygon(points = [
            [1, 0],
            [2.5, 4],
            [2.91667, 2.93169],
            [3.33333, 2.06011],
            [3.75, 1.38525],
            [4.16667, 0.9071],
            [4.58333, 0.62568],
            [5, 0.54099],
            [5.41667, 0.65301],
            [5.83333, 0.96175],
            [6.25, 1.46722],
            [6.66667, 2.1694],
            [7.08333, 3.06831],
            [7.5, 4.16394],
            [9, 0]
    ]);
    translate([5, 15]) circle(r = 2, $fn = 64);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() mirror([1, 0, 0]) FundamentalRemains();
        weld() mirror([0, 1, 0]) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*20 + j*0, i*0 + j*30, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([7.5, 100, 0]) scale(1.5) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
