// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: cm — *×  (reference: cm_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0.4, 0], [0, 0.5], [0, -0.5]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0.1974, -0.2012],
            [0.17995, -0.16709],
            [0.16567, -0.13313],
            [0.15457, -0.0993],
            [0.14663, -0.06563],
            [0.14187, -0.03209],
            [0.14029, 0.0013],
            [0.14187, 0.03454],
            [0.14663, 0.06764],
            [0.15457, 0.1006],
            [0.16567, 0.13341],
            [0.17995, 0.16608],
            [0.1974, 0.19861],
            [0, 0]
    ]);
    translate([0, 0.5]) circle(r = 0.20519, $fn = 64);
    translate([0, -0.5]) circle(r = 0.20799, $fn = 64);
    translate([0.4, 0]) circle(r = 0.1046, $fn = 64);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() mirror([1, 0, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*0.8 + j*0.4, i*0 + j*0.5, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
