// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: pgg — 22×  (reference: pgg_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[-0.5, 0], [0, 0.5], [0.5, 0]]);
}

module FundamentalCut()
{
    polygon(points = [
            [-0.43615, 0.10029],
            [-0.38959, 0.07112],
            [-0.35026, 0.04851],
            [-0.31819, 0.03246],
            [-0.29337, 0.02298],
            [-0.27579, 0.02006],
            [-0.26546, 0.0237],
            [-0.26237, 0.03391],
            [-0.26654, 0.05067],
            [-0.27795, 0.074],
            [-0.29661, 0.10389],
            [-0.32252, 0.14035],
            [-0.35567, 0.18337],
            [-0.43615, 0.10029],
            [-0.43615, 0.10029]
    ]);
    polygon(points = [
            [-0.32452, 0.2249],
            [-0.2433, 0.15816],
            [-0.17531, 0.10505],
            [-0.12056, 0.06556],
            [-0.07904, 0.03971],
            [-0.05075, 0.02749],
            [-0.0357, 0.02889],
            [-0.03388, 0.04393],
            [-0.04529, 0.0726],
            [-0.06993, 0.11489],
            [-0.10781, 0.17082],
            [-0.15892, 0.24037],
            [-0.22327, 0.32356],
            [-0.32452, 0.2249]
    ]);
    polygon(points = [
            [-0.18692, 0.3599],
            [-0.05964, 0.25909],
            [0.04615, 0.17817],
            [0.13046, 0.11716],
            [0.19327, 0.07606],
            [0.23459, 0.05486],
            [0.25442, 0.05356],
            [0.25276, 0.07216],
            [0.22962, 0.11067],
            [0.18498, 0.16909],
            [0.11885, 0.2474],
            [0.03123, 0.34563],
            [-0.07788, 0.46375],
            [-0.18692, 0.3599]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
        weld() translate([-0.5, -0.5]) mirror([1, 0, 0]) FundamentalRemains();
        weld() translate([0.5, 0.5]) mirror([0, 1, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
