// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: pg — ××  (reference: pg_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0.5], [0.15, 0.5], [0.15, -0.5], [0, -0.5]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0, -0.46125],
            [0, 0.00606],
            [0.09317, -0.10558],
            [0.08102, -0.13264],
            [0.06967, -0.16017],
            [0.05912, -0.18817],
            [0.04936, -0.21663],
            [0.0404, -0.24557],
            [0.03224, -0.27498],
            [0.02487, -0.30485],
            [0.0183, -0.33519],
            [0.01253, -0.366],
            [0.00756, -0.39728],
            [0.00338, -0.42903],
            [0, -0.46125]
    ]);
    polygon(points = [
            [0.15, 0.26567],
            [0.15, 0.00606],
            [0.09317, 0.07356],
            [0.07572, 0.10111],
            [0.0623, 0.13011],
            [0.05291, 0.16057],
            [0.04756, 0.19248],
            [0.04625, 0.22584],
            [0.04897, 0.26065],
            [0.05572, 0.29691],
            [0.06651, 0.33463],
            [0.08133, 0.37379],
            [0.10018, 0.41441],
            [0.12307, 0.45648],
            [0.15, 0.5],
            [0.15, 0.5]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0.15, 0]) mirror([0, 1, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*0.3 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(35) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
