// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p3 — 333  (reference: p3_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[-0.25, 0.43301], [0.25, 0.14434], [0.25, -0.43301], [-0.25, -0.14434]]);
}

module FundamentalCut()
{
    polygon(points = [
            [-0.08499, 0.29293],
            [-0.11883, 0.27037],
            [-0.13328, 0.23424],
            [-0.13328, -0.0822],
            [-0.11892, -0.11452],
            [-0.09507, -0.1344],
            [-0.04096, -0.13801],
            [-0.01042, -0.1151],
            [0.00124, -0.09179],
            [0.0045, -0.01686],
            [-0.05171, -0.01686],
            [-0.05419, -0.07379],
            [-0.06549, -0.08399],
            [-0.07482, -0.07732],
            [-0.07754, 0.08268],
            [-0.07077, 0.09081],
            [-0.06105, 0.09081],
            [-0.05419, 0.08258],
            [-0.05171, 0.0281],
            [0.0045, 0.0281],
            [0.00439, 0.09967],
            [-0.00712, 0.12654],
            [-0.03798, 0.14968],
            [-0.07763, 0.14735],
            [-0.07763, 0.23121],
            [-0.07059, 0.23825],
            [-0.06296, 0.23952],
            [-0.05732, 0.23613],
            [-0.04677, 0.20798],
            [-0.00175, 0.20798],
            [0.00527, 0.23605],
            [-0.01364, 0.27387],
            [-0.04413, 0.29293]
    ]);
    polygon(points = [
            [0.13328, 0.15525],
            [-0.00146, 0.15525],
            [-0.00146, 0.10011],
            [0.07779, 0.09728],
            [0.00737, -0.29293],
            [0.06045, -0.29293],
            [0.13328, 0.08943]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(120) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(240) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() FundamentalRemains();
        weld() translate([-0.25, -0.14434]) rotate(120) translate([0.25, 0.14434]) FundamentalRemains();
        weld() translate([-0.25, -0.14434]) rotate(240) translate([0.25, 0.14434]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*-0.5, i*0 + j*0.86603, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
