// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: pmg — 22*  (reference: pmg_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [0, 0.5], [0.5, 0.5], [0.5, 0]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0, 0.5],
            [0.4512, 0.5],
            [0.13966, 0.26882]
    ]);
    polygon(points = [
            [0.4512, 0.44925],
            [0.05269, 0.05075],
            [0.4512, 0.05075]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0, 0.5]) mirror([0, 1, 0]) mirror([1, 0, 0]) FundamentalRemains();
        weld() translate([0, -0.5]) mirror([1, 0, 0]) FundamentalRemains();
        weld() mirror([0, 1, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
