// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p3 — 333  (reference: p3_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[-0.25, 0.43301], [0.25, 0.14434], [0.25, -0.43301], [-0.25, -0.14434]]);
}

module FundamentalCut()
{
    polygon(points = [
            [-0.13715, 0.14434],
            [-0.07469, 0.16688],
            [-0.01772, 0.17658],
            [0.03375, 0.17343],
            [0.07974, 0.15743],
            [0.12024, 0.12859],
            [0.15524, 0.0869],
            [0.18476, 0.03237],
            [0.20879, -0.03502],
            [0.22733, -0.11525],
            [0.24037, -0.20832],
            [0.24793, -0.31424],
            [0.25, -0.43301],
            [0.15917, -0.35888],
            [0.08318, -0.29243],
            [0.02203, -0.23366],
            [-0.02429, -0.18258],
            [-0.05576, -0.13919],
            [-0.0724, -0.10348],
            [-0.0742, -0.07545],
            [-0.06116, -0.05511],
            [-0.03328, -0.04245],
            [0.00944, -0.03748],
            [0.067, -0.04019],
            [0.1394, -0.05059]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(120) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(240) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() FundamentalRemains();
        weld() translate([-0.25, -0.14434]) rotate(120) translate([0.25, 0.14434]) FundamentalRemains();
        weld() translate([-0.25, -0.14434]) rotate(240) translate([0.25, 0.14434]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*-0.5, i*0 + j*0.86603, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
