// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p31m — 3*3  (reference: p31m_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0.25, 0.14434], [-0.25, 0.43301], [0.75, 0.43301]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0.63423, 0.14434],
            [0.49923, -0.03757],
            [0.43173, -0.157]
    ]);
    polygon(points = [
            [0.05788, 0.248],
            [0.25, 0.3856],
            [0.67837, 0.43301],
            [-0.10567, 0.43301]
    ]);
    polygon(points = [
            [0.25, 0.08185],
            [0.2, 0.1805],
            [0.25, 0.32589],
            [0.3, 0.1805]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(120) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() translate([0.25, 0.14434]) rotate(240) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() mirror([0.86603, 0.5, 0]) FundamentalRemains();
        weld() mirror([0.86603, 0.5, 0]) translate([0.25, 0.14434]) rotate(120) translate([-0.25, -0.14434]) FundamentalRemains();
        weld() mirror([0.86603, 0.5, 0]) translate([0.25, 0.14434]) rotate(240) translate([-0.25, -0.14434]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0.5, i*0 + j*0.86603, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
