// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: cmm — 2*22  (reference: cmm_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [0.6, 0], [0, 0.8]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0, 0.72262],
            [0.0073, 0.61701],
            [0.01782, 0.51966],
            [0.03156, 0.43056],
            [0.04851, 0.34971],
            [0.06869, 0.27711],
            [0.09208, 0.21277],
            [0.11869, 0.15668],
            [0.14851, 0.10884],
            [0.18156, 0.06925],
            [0.21782, 0.03791],
            [0.2573, 0.01483],
            [0.3, 0],
            [0, 0]
    ]);
    polygon(points = [
            [0.05285, 0.65408],
            [0.07475, 0.54478],
            [0.09963, 0.44604],
            [0.12749, 0.35786],
            [0.15831, 0.28023],
            [0.1921, 0.21316],
            [0.22887, 0.15665],
            [0.2686, 0.1107],
            [0.31131, 0.07531],
            [0.35699, 0.05047],
            [0.40563, 0.03619],
            [0.45725, 0.03247],
            [0.51185, 0.03931],
            [0.47488, 0.05748],
            [0.43875, 0.08015],
            [0.40346, 0.10733],
            [0.369, 0.139],
            [0.33538, 0.17517],
            [0.3026, 0.21585],
            [0.27065, 0.26102],
            [0.23954, 0.31069],
            [0.20926, 0.36487],
            [0.17983, 0.42354],
            [0.15123, 0.48671],
            [0.12346, 0.55438]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() mirror([1, 0, 0]) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
        weld() mirror([0, 1, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1.2 + j*0.6, i*0 + j*0.8, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
