// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p4 — 442  (reference: p4_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [0, 0.5], [0.5, 0.5], [0.5, 0]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0.25, 0.24805],
            [0.25, 0.5],
            [0, 0.5],
            [0.02902, 0.4901],
            [0.05656, 0.47818],
            [0.0826, 0.46425],
            [0.10716, 0.4483],
            [0.13023, 0.43033],
            [0.1518, 0.41034],
            [0.17189, 0.38834],
            [0.19049, 0.36432],
            [0.2076, 0.33828],
            [0.22322, 0.31022],
            [0.23736, 0.28015],
            [0.25, 0.24805]
    ]);
    polygon(points = [
            [0, 0.152],
            [0.25, 0.152],
            [0.25, 0],
            [0.21039, -0.00018],
            [0.17419, -0.00033],
            [0.1414, -0.00044],
            [0.11203, -0.00052],
            [0.08607, -0.00057],
            [0.06353, -0.00059],
            [0.04441, -0.00057],
            [0.0287, -0.00052],
            [0.0164, -0.00044],
            [0.00752, -0.00033],
            [0.00205, -0.00018],
            [0, 0]
    ]);
    translate([0.37332, 0.36877]) circle(r = 0.07435, $fn = 64);
    translate([0.0449, 0.59464]) circle(r = 0.01981, $fn = 64);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() rotate(90) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
        weld() rotate(270) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
