// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: cm — *×  (reference: cm_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0.4, 0], [0, 0.5], [0, -0.5]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0, 0.19817],
            [0.01633, 0.11567],
            [0.03327, 0.04817],
            [0.05083, -0.00433],
            [0.069, -0.04183],
            [0.08777, -0.06433],
            [0.10716, -0.07183],
            [0.12716, -0.06433],
            [0.14778, -0.04183],
            [0.169, -0.00433],
            [0.19084, 0.04817],
            [0.21329, 0.11567],
            [0.23635, 0.19817],
            [0.25084, 0.16031],
            [0.26058, 0.12115],
            [0.26555, 0.0807],
            [0.26577, 0.03894],
            [0.26123, -0.00411],
            [0.25192, -0.04846],
            [0.23786, -0.09411],
            [0.21904, -0.14106],
            [0.19546, -0.1893],
            [0.16712, -0.23885],
            [0.13401, -0.28969],
            [0.09615, -0.34183],
            [0.06415, -0.30873],
            [0.03651, -0.27346],
            [0.01323, -0.23603],
            [-0.00568, -0.19644],
            [-0.02024, -0.15469],
            [-0.03043, -0.11077],
            [-0.03626, -0.06469],
            [-0.03774, -0.01644],
            [-0.03484, 0.03397],
            [-0.02759, 0.08654],
            [-0.01598, 0.14127],
            [0, 0.19817]
    ]);
    polygon(points = [
            [0, 0.28125],
            [0.01839, 0.23921],
            [0.03544, 0.20481],
            [0.05115, 0.17805],
            [0.06553, 0.15894],
            [0.07858, 0.14748],
            [0.09029, 0.14365],
            [0.10066, 0.14748],
            [0.1097, 0.15894],
            [0.1174, 0.17805],
            [0.12377, 0.20481],
            [0.1288, 0.23921],
            [0.1325, 0.28125],
            [0, 0.43702]
    ]);
    translate([0, -0.37817]) circle(r = 0.04442, $fn = 64);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() mirror([1, 0, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*0.8 + j*0.4, i*0 + j*0.5, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(40) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
