// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: p4g — 4*2  (reference: p4g_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [0.5, 0], [0, 0.5]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0.05269, 0.04923],
            [0.01894, 0.19202],
            [0.07865, 0.07649],
            [0.19808, 0.01938]
    ]);
    polygon(points = [
            [0.01894, 0.22707],
            [0.01894, 0.44255],
            [0.01894, 0.44255],
            [0.15005, 0.29976],
            [0.05269, 0.36466]
    ]);
    polygon(points = [
            [0.44341, 0.01938],
            [0.3188, 0.14659],
            [0.36423, 0.04923],
            [0.25519, 0.01938]
    ]);
    polygon(points = [
            [0.07865, 0.29976],
            [0.08442, 0.28572],
            [0.08875, 0.27261],
            [0.09163, 0.26041],
            [0.09308, 0.24913],
            [0.09308, 0.23878],
            [0.09163, 0.22934],
            [0.08875, 0.22082],
            [0.08442, 0.21322],
            [0.07865, 0.20654],
            [0.07144, 0.20078],
            [0.06279, 0.19594],
            [0.05269, 0.19202],
            [0.06549, 0.18678],
            [0.07663, 0.18102],
            [0.08612, 0.17474],
            [0.09394, 0.16793],
            [0.10011, 0.1606],
            [0.10462, 0.15275],
            [0.10746, 0.14438],
            [0.10865, 0.13548],
            [0.10819, 0.12606],
            [0.10606, 0.11612],
            [0.10227, 0.10565],
            [0.09683, 0.09466],
            [0.10961, 0.10149],
            [0.122, 0.10638],
            [0.13398, 0.10935],
            [0.14558, 0.11038],
            [0.15677, 0.10949],
            [0.16757, 0.10667],
            [0.17797, 0.10192],
            [0.18798, 0.09524],
            [0.19759, 0.08663],
            [0.2068, 0.07609],
            [0.21562, 0.06363],
            [0.22404, 0.04923],
            [0.2241, 0.06489],
            [0.22559, 0.07811],
            [0.2285, 0.0889],
            [0.23284, 0.09726],
            [0.2386, 0.10318],
            [0.24578, 0.10667],
            [0.25439, 0.10773],
            [0.26442, 0.10635],
            [0.27588, 0.10253],
            [0.28876, 0.09629],
            [0.30307, 0.08761],
            [0.3188, 0.07649],
            [0.30309, 0.09018],
            [0.2897, 0.10314],
            [0.27864, 0.11535],
            [0.2699, 0.12683],
            [0.26349, 0.13756],
            [0.25941, 0.14756],
            [0.25765, 0.15682],
            [0.25822, 0.16534],
            [0.26111, 0.17312],
            [0.26633, 0.18016],
            [0.27388, 0.18646],
            [0.28375, 0.19202],
            [0.26436, 0.18965],
            [0.24686, 0.18903],
            [0.23126, 0.19015],
            [0.21755, 0.19303],
            [0.20573, 0.19765],
            [0.19581, 0.20403],
            [0.18777, 0.21215],
            [0.18163, 0.22202],
            [0.17739, 0.23364],
            [0.17504, 0.24701],
            [0.17458, 0.26212],
            [0.17601, 0.27899],
            [0.16958, 0.26803],
            [0.16285, 0.25938],
            [0.15581, 0.25303],
            [0.14846, 0.24899],
            [0.14081, 0.24726],
            [0.13285, 0.24784],
            [0.12458, 0.25072],
            [0.11601, 0.25591],
            [0.10713, 0.26341],
            [0.09794, 0.27322],
            [0.08845, 0.28534],
            [0.07865, 0.29976]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0.5, 0.5]) mirror([1, 1, 0]) FundamentalRemains();
        weld() rotate(90) FundamentalRemains();
        weld() rotate(90) translate([0.5, 0.5]) mirror([1, 1, 0]) FundamentalRemains();
        weld() rotate(180) FundamentalRemains();
        weld() rotate(180) translate([0.5, 0.5]) mirror([1, 1, 0]) FundamentalRemains();
        weld() rotate(270) FundamentalRemains();
        weld() rotate(270) translate([0.5, 0.5]) mirror([1, 1, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(50) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
