// Auto-generated by OpenSCAD Wallpaper Pattern Editor
// Wallpaper group: pmg — 22*  (reference: pmg_Template.scad)

$fn = 48;
epsilon = 0.0001;

module weld() { offset(delta = epsilon) children(); }

module FundamentalDomain()
{
    polygon(points = [[0, 0], [0, 0.5], [0.5, 0.5], [0.5, 0]]);
}

module FundamentalCut()
{
    polygon(points = [
            [0.20067, 0.29976],
            [0.0501, 0.41139],
            [0.0501, 0.15178],
            [0.06701, 0.17076],
            [0.08312, 0.18445],
            [0.09845, 0.19283],
            [0.11298, 0.19591],
            [0.12672, 0.1937],
            [0.13966, 0.18618],
            [0.15181, 0.17336],
            [0.16317, 0.15524],
            [0.17374, 0.13182],
            [0.18351, 0.1031],
            [0.19249, 0.06908],
            [0.20067, 0.02976]
    ]);
    polygon(points = [
            [0.11889, 0.44514],
            [0.25, 0.34909],
            [0.34865, 0.34909],
            [0.29933, 0.25043],
            [0.30211, 0.2085],
            [0.30743, 0.17269],
            [0.31528, 0.14302],
            [0.32566, 0.11947],
            [0.33858, 0.10206],
            [0.35404, 0.09077],
            [0.37203, 0.08561],
            [0.39255, 0.08659],
            [0.41561, 0.09369],
            [0.44121, 0.10692],
            [0.46934, 0.12629],
            [0.5, 0.15178],
            [0.40058, 0.25043],
            [0.40058, 0.44514]
    ]);
}

module FundamentalRemains()
{
    difference() { FundamentalDomain(); FundamentalCut(); }
}

module CompiledTile()
{
    union()
    {
        weld() FundamentalRemains();
        weld() translate([0, 0.5]) mirror([0, 1, 0]) mirror([1, 0, 0]) FundamentalRemains();
        weld() translate([0, -0.5]) mirror([1, 0, 0]) FundamentalRemains();
        weld() mirror([0, 1, 0]) FundamentalRemains();
    }
}

module PatternArray()
{
    for (i = [-10:1:10])
        for (j = [-10:1:10])
            translate([i*1 + j*0, i*0 + j*1, 0])
                CompiledTile();
}

//----------------------------

base = 150;
phi = (1 + sqrt(5)) / 2;
holeGap = 8;

leftBase = [-base/2, 0];
rightBase = [base/2, 0];
side = phi * base;
height = sqrt(side*side - (base/2)*(base/2));
apex = [0, height];

module GoldenTriangle()
{
    polygon(points = [leftBase, rightBase, apex]);
}

difference()
{
    GoldenTriangle();
    difference()
    {
        offset(delta = -12) GoldenTriangle();
        render() translate([0, 100, 0]) scale(30) PatternArray();
    }
    translate([(-base/2)+holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([(base/2)-holeGap*cos(36), holeGap*sin(36)]) circle(r = 2, $fn = 100);
    translate([0, height - holeGap * 2]) circle(r = 2, $fn = 100);
    polygon(points = [[-10, 7], [10, 7], [10, 11], [-10, 11]]);
}
