#!/usr/bin/env python3
"""Pack every Complete_NN panel's DXF into interlocking golden-triangle
nesting sheets (alternating up/down orientation, evenly gapped) sized to
fit a laser bed, spilling into additional sheets as needed.

Usage: python Tools/gen_nested_sheets.py [--exclude 1-7,14,33] [--out Nested/Batch_02]
  --exclude  panel numbers to leave out (e.g. ones already cut)
  --out      output directory (default: Nested/)
"""
import os, re, glob, math, subprocess, sys, argparse

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OSCAD = os.environ.get("OPENSCAD", r"C:\Program Files (x86)\OpenSCAD\openscad.exe")
DXF_DIR = os.path.join(REPO, "DXF")


def parse_ranges(spec):
    nums = set()
    for part in filter(None, (p.strip() for p in spec.split(","))):
        a, _, b = part.partition("-")
        nums.update(range(int(a), int(b or a) + 1))
    return nums


ap = argparse.ArgumentParser()
ap.add_argument("--exclude", default="", help="panel numbers to skip, e.g. 1-7,14-20,33")
ap.add_argument("--out", default=os.path.join(REPO, "Nested"), help="output directory")
args = ap.parse_args()
EXCLUDE = parse_ranges(args.exclude)
OUT_DIR = os.path.abspath(args.out)
os.makedirs(OUT_DIR, exist_ok=True)

# Golden-triangle geometry (must match GoldenTriangle_Blank_Template.scad)
BASE = 150.0
PHI = (1 + 5 ** 0.5) / 2
SIDE = PHI * BASE
HEIGHT = math.sqrt(SIDE ** 2 - (BASE / 2) ** 2)

# Laser bed / sheet stock
SHEET_W, SHEET_H = 1200.0, 600.0
PAD = 20.0

# Uniform gap left between adjacent triangle edges (perpendicular distance,
# not just a raw translate) -- see commit message for the trig behind it.
GAP = 3.0

# Horizontal step per column: base/2 (interlock pitch) plus however much
# extra horizontal shift is needed so the two parallel slanted edges end up
# GAP apart (perpendicular distance = horizontal shift * SIDE/HEIGHT).
COL_PITCH = BASE / 2 + GAP * SIDE / HEIGHT
# Vertical step per row: the row's own height plus a plain vertical GAP,
# since row-to-row seams are horizontal (perpendicular = vertical shift).
ROW_PITCH = HEIGHT + GAP

USABLE_W = SHEET_W - 2 * PAD
USABLE_H = SHEET_H - 2 * PAD


def fit_count(first_extent, pitch, usable):
    n = 1
    while first_extent + (n - 1) * pitch <= usable:
        n += 1
    return n - 1


ROWS = fit_count(HEIGHT, ROW_PITCH, USABLE_H)
COLS = fit_count(BASE, COL_PITCH, USABLE_W)
PER_SHEET = ROWS * COLS

def panel_num(p):
    return int(re.match(r"Complete_(\d+)", os.path.basename(p)).group(1))


files = sorted(glob.glob(os.path.join(DXF_DIR, "Complete_*.dxf")), key=panel_num)
files = [p for p in files if panel_num(p) not in EXCLUDE]

print(f"triangle base={BASE} height={HEIGHT:.2f}")
print(f"sheet usable {USABLE_W}x{USABLE_H} -> {COLS} cols x {ROWS} rows = {PER_SHEET}/sheet")
print(f"{len(files)} panels -> {math.ceil(len(files)/PER_SHEET)} sheet(s)")

sheet_idx = 0
manifest_lines = []
for start in range(0, len(files), PER_SHEET):
    sheet_idx += 1
    batch = files[start:start + PER_SHEET]
    lines = [
        "// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit",
        f"// Golden-triangle nesting sheet {sheet_idx}: {len(batch)} panels, "
        f"stock {SHEET_W:.0f}x{SHEET_H:.0f}mm, {PAD:.0f}mm edge padding, {GAP:.0f}mm inter-panel gap",
        "",
    ]
    for i, path in enumerate(batch):
        r, k = divmod(i, COLS)
        cx = PAD + BASE / 2 + k * COL_PITCH
        row_y = PAD + r * ROW_PITCH
        up = (r + k) % 2 == 0
        dxf_path = path.replace("\\", "/")
        if up:
            lines.append(f'translate([{cx:.4f}, {row_y:.4f}]) import("{dxf_path}");')
        else:
            cy = row_y + HEIGHT
            lines.append(f'translate([{cx:.4f}, {cy:.4f}]) rotate([0,0,180]) import("{dxf_path}");')
        manifest_lines.append(f"sheet {sheet_idx:02d}  row {r}  col {k:2d}  "
                               f"{'up  ' if up else 'down'}  {os.path.basename(path)}")

    scad_path = os.path.join(OUT_DIR, f"Sheet_{sheet_idx:02d}.scad")
    with open(scad_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    dxf_out = os.path.join(OUT_DIR, f"Sheet_{sheet_idx:02d}.dxf")
    png_out = os.path.join(OUT_DIR, f"Sheet_{sheet_idx:02d}_preview.png")
    print(f"rendering sheet {sheet_idx} ({len(batch)} panels)...")
    r1 = subprocess.run([OSCAD, "-o", dxf_out, scad_path], capture_output=True, text=True)
    if r1.returncode != 0:
        print(r1.stderr[-2000:]); sys.exit(1)
    cam = f"{SHEET_W/2},{SHEET_H/2},0,0,0,0,{SHEET_W*1.15}"
    r2 = subprocess.run([OSCAD, "-o", png_out, "--imgsize=2400,1200",
                         "--projection=o", f"--camera={cam}", scad_path],
                         capture_output=True, text=True)
    if r2.returncode != 0:
        print(r2.stderr[-2000:]); sys.exit(1)

with open(os.path.join(OUT_DIR, "manifest.txt"), "w") as f:
    f.write(f"Golden-triangle nesting manifest -- stock {SHEET_W:.0f}x{SHEET_H:.0f}mm, "
            f"{PAD:.0f}mm edge padding, {GAP:.0f}mm inter-panel gap, "
            f"{COLS} cols x {ROWS} rows = {PER_SHEET} panels/sheet\n\n")
    f.write("\n".join(manifest_lines) + "\n")

print(f"wrote {sheet_idx} sheet(s) to {OUT_DIR}")
