#!/usr/bin/env python3
"""Pack every Complete_NN panel's DXF into interlocking golden-triangle
nesting sheets (alternating up/down orientation, zero-gap) sized to fit
a laser bed, spilling into additional sheets as needed.

Usage: python Tools/gen_nested_sheets.py
"""
import os, re, glob, math, subprocess, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OSCAD = os.environ.get("OPENSCAD", r"C:\Program Files (x86)\OpenSCAD\openscad.exe")
DXF_DIR = os.path.join(REPO, "DXF")
OUT_DIR = os.path.join(REPO, "Nested")
os.makedirs(OUT_DIR, exist_ok=True)

# Golden-triangle geometry (must match GoldenTriangle_Blank_Template.scad)
BASE = 150.0
PHI = (1 + 5 ** 0.5) / 2
SIDE = PHI * BASE
HEIGHT = math.sqrt(SIDE ** 2 - (BASE / 2) ** 2)

# Laser bed / sheet stock
SHEET_W, SHEET_H = 1200.0, 600.0
PAD = 20.0

USABLE_W = SHEET_W - 2 * PAD
USABLE_H = SHEET_H - 2 * PAD
ROWS = int(USABLE_H // HEIGHT)
COLS = int((USABLE_W - BASE) // (BASE / 2)) + 1
PER_SHEET = ROWS * COLS

files = sorted(glob.glob(os.path.join(DXF_DIR, "Complete_*.dxf")),
               key=lambda p: int(re.match(r"Complete_(\d+)", os.path.basename(p)).group(1)))

print(f"triangle base={BASE} height={HEIGHT:.2f}")
print(f"sheet usable {USABLE_W}x{USABLE_H} -> {COLS} cols x {ROWS} rows = {PER_SHEET}/sheet")
print(f"{len(files)} panels -> {math.ceil(len(files)/PER_SHEET)} sheet(s)")

sheet_idx = 0
manifest_lines = []
for start in range(0, len(files), PER_SHEET):
    sheet_idx += 1
    batch = files[start:start + PER_SHEET]
    lines = [
        "// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit",
        f"// Golden-triangle nesting sheet {sheet_idx}: {len(batch)} panels, "
        f"stock {SHEET_W:.0f}x{SHEET_H:.0f}mm, {PAD:.0f}mm edge padding",
        "",
    ]
    for i, path in enumerate(batch):
        r, k = divmod(i, COLS)
        cx = PAD + BASE / 2 + k * (BASE / 2)
        up = (r + k) % 2 == 0
        dxf_path = path.replace("\\", "/")
        if up:
            cy = PAD + r * HEIGHT
            lines.append(f'translate([{cx:.4f}, {cy:.4f}]) import("{dxf_path}");')
        else:
            cy = PAD + r * HEIGHT + HEIGHT
            lines.append(f'translate([{cx:.4f}, {cy:.4f}]) rotate([0,0,180]) import("{dxf_path}");')
        manifest_lines.append(f"sheet {sheet_idx:02d}  row {r}  col {k:2d}  "
                               f"{'up  ' if up else 'down'}  {os.path.basename(path)}")

    scad_path = os.path.join(OUT_DIR, f"Sheet_{sheet_idx:02d}.scad")
    with open(scad_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    dxf_out = os.path.join(OUT_DIR, f"Sheet_{sheet_idx:02d}.dxf")
    png_out = os.path.join(OUT_DIR, f"Sheet_{sheet_idx:02d}_preview.png")
    print(f"rendering sheet {sheet_idx} ({len(batch)} panels)...")
    r1 = subprocess.run([OSCAD, "-o", dxf_out, scad_path], capture_output=True, text=True)
    if r1.returncode != 0:
        print(r1.stderr[-2000:]); sys.exit(1)
    cam = f"{SHEET_W/2},{SHEET_H/2},0,0,0,0,{SHEET_W*1.15}"
    r2 = subprocess.run([OSCAD, "-o", png_out, "--imgsize=2400,1200",
                         "--projection=o", f"--camera={cam}", scad_path],
                         capture_output=True, text=True)
    if r2.returncode != 0:
        print(r2.stderr[-2000:]); sys.exit(1)

with open(os.path.join(OUT_DIR, "manifest.txt"), "w") as f:
    f.write(f"Golden-triangle nesting manifest -- stock {SHEET_W:.0f}x{SHEET_H:.0f}mm, "
            f"{PAD:.0f}mm edge padding, {COLS} cols x {ROWS} rows = {PER_SHEET} panels/sheet\n\n")
    f.write("\n".join(manifest_lines) + "\n")

print(f"wrote {sheet_idx} sheet(s) to {OUT_DIR}")
