// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 1: 28 panels, stock 1200x600mm, 20mm edge padding

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_01_CairoTiling.dxf");
translate([170.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_02_CircleFower.dxf");
translate([245.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_03_CircleFowerPetals.dxf");
translate([320.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_04_CompositeHexagon.dxf");
translate([395.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_05_CompositeHexagonStar.dxf");
translate([470.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_06_DoubleCircleFan.dxf");
translate([545.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_07_EchoSquare.dxf");
translate([620.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_08_Hexagons.dxf");
translate([695.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_09_HexagonShutter.dxf");
translate([770.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_10_HexStar.dxf");
translate([845.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_11_Icurl.dxf");
translate([920.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_12_MantaRay.dxf");
translate([995.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_13_plus_shape_tiling.dxf");
translate([1070.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_14_SpiralColideWideVisibleSideCross.dxf");
translate([95.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_15_Square Stairs.dxf");
translate([170.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_16_TiltedWindows.dxf");
translate([245.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_17_tristar.dxf");
translate([320.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_18_tristar_HexagonWreath.dxf");
translate([395.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_19_tumblinblocksv3.dxf");
translate([470.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_20_WaveBall.dxf");
translate([545.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_21_PolyominoWeave.dxf");
translate([620.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_22_p4m_ThreeShapesInAGrid.dxf");
translate([695.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_23_SlopeField.dxf");
translate([770.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_24_p4_HalfMoonSpin.dxf");
translate([845.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_25_p4g_ComeWhirl.dxf");
translate([920.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_26_p4g_KeyPinwheel.dxf");
translate([995.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_27_HoundsTooth.dxf");
translate([1070.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_28_JapaneseArrowsFletch.dxf");
