// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 3: 4 panels, stock 1200x600mm, 20mm edge padding

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_57_cm_TriGridMesh.dxf");
translate([170.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_58_pg_SnakeSkin.dxf");
translate([245.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_59_p31m_TadpoleTri.dxf");
translate([320.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_60_pmm_DiamondEye.dxf");
