// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 3: 8 panels, stock 1200x600mm, 20mm edge padding, 3mm inter-panel gap

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_53_cmm_ParenthesisDiamond.dxf");
translate([173.1544, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_54_cm_ScaleShells.dxf");
translate([251.3088, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_55_p6m_SixFoldTriMesh.dxf");
translate([329.4632, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_56_p3m1_TriDiamondMesh.dxf");
translate([407.6175, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_57_cm_TriGridMesh.dxf");
translate([485.7719, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_58_pg_SnakeSkin.dxf");
translate([563.9263, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_59_p31m_TadpoleTri.dxf");
translate([642.0807, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_60_pmm_DiamondEye.dxf");
