// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 1: 26 panels, stock 1200x600mm, 20mm edge padding, 3mm inter-panel gap

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_01_CairoTiling.dxf");
translate([173.1544, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_02_CircleFower.dxf");
translate([251.3088, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_03_CircleFowerPetals.dxf");
translate([329.4632, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_04_CompositeHexagon.dxf");
translate([407.6175, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_05_CompositeHexagonStar.dxf");
translate([485.7719, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_06_DoubleCircleFan.dxf");
translate([563.9263, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_07_EchoSquare.dxf");
translate([642.0807, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_08_Hexagons.dxf");
translate([720.2351, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_09_HexagonShutter.dxf");
translate([798.3895, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_10_HexStar.dxf");
translate([876.5439, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_11_Icurl.dxf");
translate([954.6983, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_12_MantaRay.dxf");
translate([1032.8526, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_13_plus_shape_tiling.dxf");
translate([95.0000, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_14_SpiralColideWideVisibleSideCross.dxf");
translate([173.1544, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_15_Square Stairs.dxf");
translate([251.3088, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_16_TiltedWindows.dxf");
translate([329.4632, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_17_tristar.dxf");
translate([407.6175, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_18_tristar_HexagonWreath.dxf");
translate([485.7719, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_19_tumblinblocksv3.dxf");
translate([563.9263, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_20_WaveBall.dxf");
translate([642.0807, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_21_PolyominoWeave.dxf");
translate([720.2351, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_22_p4m_ThreeShapesInAGrid.dxf");
translate([798.3895, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_23_SlopeField.dxf");
translate([876.5439, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_24_p4_HalfMoonSpin.dxf");
translate([954.6983, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_25_p4g_ComeWhirl.dxf");
translate([1032.8526, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_26_p4g_KeyPinwheel.dxf");
