// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 2: 26 panels, stock 1200x600mm, 20mm edge padding, 3mm inter-panel gap

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_27_HoundsTooth.dxf");
translate([173.1544, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_28_JapaneseArrowsFletch.dxf");
translate([251.3088, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_29_p3_SlottedTriangle.dxf");
translate([329.4632, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_30_p6m_SayakaTriStar.dxf");
translate([407.6175, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_31_p2_OceanCurve.dxf");
translate([485.7719, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_32_EightStar.dxf");
translate([563.9263, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_33_EightStarShifter.dxf");
translate([642.0807, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_34_EightStarSplit.dxf");
translate([720.2351, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_35_pmm_HandMirror.dxf");
translate([798.3895, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_36_MapleQuilt.dxf");
translate([876.5439, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_37_RhombusEight.dxf");
translate([954.6983, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_38_p4_PinwheelsAndShrukens.dxf");
translate([1032.8526, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_39_CairoAttempt4.dxf");
translate([95.0000, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_40_p6_BubbleFlowers.dxf");
translate([173.1544, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_41_StickerPile.dxf");
translate([251.3088, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_42_cm_BowtieButterfly.dxf");
translate([329.4632, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_43_p3_SpikyPinwheel.dxf");
translate([407.6175, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_44_p4_FourDice.dxf");
translate([485.7719, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_45_pmg_PointAndPierce.dxf");
translate([563.9263, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_46_p6_LeafCorners.dxf");
translate([642.0807, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_47_p31m_IDontKnowMan.dxf");
translate([720.2351, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_48_p3_SixtySeven.dxf");
translate([798.3895, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_49_pmg_EmptyReverseWriting.dxf");
translate([876.5439, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_50_pgg_FingerSquares.dxf");
translate([954.6983, 253.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_51_p4g_HollyStar.dxf");
translate([1032.8526, 484.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_52_p4m_InvisibleIntersection.dxf");
