// Auto-generated by Tools/gen_nested_sheets.py -- do not hand-edit
// Golden-triangle nesting sheet 2: 28 panels, stock 1200x600mm, 20mm edge padding

translate([95.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_29_p3_SlottedTriangle.dxf");
translate([170.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_30_p6m_SayakaTriStar.dxf");
translate([245.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_31_p2_OceanCurve.dxf");
translate([320.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_32_EightStar.dxf");
translate([395.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_33_EightStarShifter.dxf");
translate([470.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_34_EightStarSplit.dxf");
translate([545.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_35_pmm_HandMirror.dxf");
translate([620.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_36_MapleQuilt.dxf");
translate([695.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_37_RhombusEight.dxf");
translate([770.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_38_p4_PinwheelsAndShrukens.dxf");
translate([845.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_39_CairoAttempt4.dxf");
translate([920.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_40_p6_BubbleFlowers.dxf");
translate([995.0000, 20.0000]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_41_StickerPile.dxf");
translate([1070.0000, 250.8263]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_42_cm_BowtieButterfly.dxf");
translate([95.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_43_p3_SpikyPinwheel.dxf");
translate([170.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_44_p4_FourDice.dxf");
translate([245.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_45_pmg_PointAndPierce.dxf");
translate([320.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_46_p6_LeafCorners.dxf");
translate([395.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_47_p31m_IDontKnowMan.dxf");
translate([470.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_48_p3_SixtySeven.dxf");
translate([545.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_49_pmg_EmptyReverseWriting.dxf");
translate([620.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_50_pgg_FingerSquares.dxf");
translate([695.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_51_p4g_HollyStar.dxf");
translate([770.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_52_p4m_InvisibleIntersection.dxf");
translate([845.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_53_cmm_ParenthesisDiamond.dxf");
translate([920.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_54_cm_ScaleShells.dxf");
translate([995.0000, 481.6525]) rotate([0,0,180]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_55_p6m_SixFoldTriMesh.dxf");
translate([1070.0000, 250.8263]) import("D:/LaserCutting/Wanderers-Star-Laser-Cutting-Summer/DXF/Complete_56_p3m1_TriDiamondMesh.dxf");
